{{- if .Values.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProvider.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "workstack.labels" . | nindent 4 }}
spec:
  provider: gke
  parameters:
    secrets: |
      {{- range .Values.secretProvider.secrets }}
      - resourceName: "{{ .resourceName }}"
        path: "{{ .path }}"
      {{- end }}
  secretObjects:
    - secretName: backend-secret
      type: Opaque
      data:
        {{- range .Values.secretProvider.secrets }}
        - objectName: {{ .path }}
          key: {{ .path }}
        {{- end }}
{{- end }}
