{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "workstack.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.postgres.storage.className }}
  resources:
    requests:
      storage: {{ .Values.postgres.storage.size }}
{{- end }}
