{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.serviceName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "workstack.labels" . | nindent 4 }}
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
{{- end }}
