{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "workstack.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.backendMinAvailable }}
  selector:
    matchLabels:
      app: backend
{{- end }}
