apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
  labels:
    app: backend
    {{- include "workstack.labels" . | nindent 4 }}
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
