apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: backend-secret-provider
  namespace: workstack
spec:
  provider: gke
  parameters:
    secrets: |
      - resourceName: "projects/workstack-devops-vb/secrets/workstack-dev-database-url/versions/latest"
        path: "DATABASE_URL"
      - resourceName: "projects/workstack-devops-vb/secrets/workstack-dev-app-secret-key/versions/latest"
        path: "SECRET_KEY"
  secretObjects:
    - secretName: backend-secret
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: SECRET_KEY
          key: SECRET_KEY
