apiVersion: v1
kind: ServiceAccount
metadata:
  name: workstack-backend
  namespace: workstack
  annotations:
    iam.gke.io/gcp-service-account: workstack-dev-backend@workstack-devops-vb.iam.gserviceaccount.com
